"""empty message

Revision ID: 10036b212882
Revises: 299f9f800ca8
Create Date: 2022-04-11 12:23:05.911788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10036b212882'
down_revision = '299f9f800ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('profiles', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'image')
    # ### end Alembic commands ###
