"""Changed birthday to string instead of date.

Revision ID: 39d3361ae861
Revises: 448e00becc38
Create Date: 2022-03-18 17:44:26.193956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d3361ae861'
down_revision = '448e00becc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'birthday',
                existing_type=sa.Date(),
                type_=sa.String(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'city',
                existing_type=sa.String(),
                type_=sa.Date(),
                existing_nullable=True)
    # ### end Alembic commands ###
